version: '3.4'

services:
  event-api:
    image: ${DOCKER_REGISTRY-}event-api
    container_name: Event.Api
    build:
      context: .
      dockerfile: Event.Api/Dockerfile
    ports:
      - "5001:443"

  db-event:
    image: postgres:latest
    container_name: Event.Db
    volumes:
      - ./containers/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "application"
      POSTGRES_PASSWORD: "strong_password"
      POSTGRES_DB: "db_event"
